### ISSUE TITLE
Implement Location Comparison default scenarios

### ISSUE THREAD

**Issue by edwinmp** [devinit/data-hub-spotlights#117]
https://github.com/devinit/DIwebsite-redesign/issues/689

**Comment by edwinmp** [comment]
https://github.com/devinit/data-hub-spotlights/issues/152#issuecomment-608324316

**Comment by k8hughes** [comment]
I was expected some pre selected places so it would show a user what to do.  @benjamincoleman  can you check this page and just let us know what you think?

http://157.245.39.153/spotlight/spotlight-kenya/compare?t=kenya_poverty_and_vulnerability&i=spotlight_on_kenya_2017.kenya_hdi&y=2014

**Comment by benjamincoleman** [comment]
Some comments: 

**On the start state**

- a pre-selected place or two would help. Perhaps the capital state? I would test this scenario to see how it helped people pick it up and start using it.  
- can we have the compare button disabled rather than hidden? The disabled style uses class `button--disabled`. Then folks know it's there and the button will help them understand to use some of the controls. 

We should user test this. I'd love to see some remote testing. 

**Some other observations**

- Can we sort the list of countries alphabetically? It's hard to scan in a jumbled order. 
- There's a view button that doesn't seem to do anything in the menu
- This is seriously quick, which makes me think again about the compare button. User testing is the way forwards though - I can think about some scenarios at some point when it comes to it. 

Otherwise, I absolutely love seeing this live. It's sooooooo fast, and does exactly what we believe people need. Well done!

**Comment by k8hughes** [comment]
When I land on this page it still doesn't have anything pre selected.
Is it working for you @edwinmp ?

**Comment by edwinmp** [comment]
I've configured some for both Uganda (Wakiso) and Kenya (Nairobi) ... can add more to the CMS.

**Comment by k8hughes** [comment]
Can we have two locations preselected on arrival to the page so that it is possible to see the comparison functionality?

**Comment by edwinmp** [comment]
They should both have 3 locations now ...

**Comment by k8hughes** [comment]
This is perfect, nice one!
