### ISSUE TITLE
If there's no data for a location, it's not selectable on the map

### ISSUE THREAD

**Issue by benjamincoleman** [devinit/data-hub-spotlights#162]
http://157.245.39.153/spotlight/spotlight-kenya?t=kenya_district_public_resources&i=spotlight_on_kenya_2017.kenya_agri_percent&y=2013

I can no longer use the map here - it looks like areas without data are no longer drawn on the canvas, and so are not selectable. It would be better to have them drawn there but in the no data colour. 

We could then also change the backing map colour to solve #69

**Comment by k8hughes** [comment]
We definately need to have the area drawn out even if there is no data.

**Comment by edwinmp** [comment]
Yeah, this one is weird .... shouldn't be doing that ... I'm considering this a bug.

**Comment by edwinmp** [comment]
@mariamiah besides allowing better handling for no-data situations, a proper fix for this would be what's described in issue #63. So please implement that as well.

**Comment by k8hughes** [comment]
The URL on this ticket is a weird one as we have no data for this year anywhere in Kenya, therefore shouldn't we not show this year in the drop down?
  http://157.245.39.153/spotlight/spotlight-kenya?t=kenya_district_public_resources&i=spotlight_on_kenya_2017.kenya_agri_percent&y=2013 

The bug listed on this issue is however fixed.
