### ISSUE TITLE
Key Facts section is not updated on changing from one location to another.

### ISSUE THREAD

**Issue by edwinmp** [devinit/data-hub-spotlights#185]

**Comment by k8hughes** [comment]
This is working for the scenario where I selection the location from the drop down menu but it is not working for the scenario where I select the location by clikcing on the map.

Steps to reproduce:
Go to: http://157.245.39.153/spotlight/spotlight-kenya
Click on the location you want to select on the map
Map zooms in on this area
Scroll down to key facts and you will see they are still country wide instead of showing for that location.

**Comment by edwinmp** [comment]
Selecting a location by clicking on the map was never implemented ... there's a feature request for it  #158 ...

**Comment by k8hughes** [comment]
That would explain it than :)
