### ISSUE TITLE
Investigate data inconsistencies as raised by the analysts

### ISSUE THREAD

**Issue by edwinmp** [devinit/data-hub-spotlights#225]
https://docs.google.com/spreadsheets/d/1bVaqMXMXlVnVJm3MMJpplbHVv1_ZyDUkOHZH1bF5gKE/edit#gid=0

1. Verify that the problem exists
2. Determine the source of the problem (data or front-end)
3. Create a GitHub issue for each

**Comment by k8hughes** [comment]
@wakibi can you look at this one?  Maybe these are all fixed.

**Comment by wakibi** [comment]
On second thought, I think it would make more sense to edit the README files for both [SoK](https://github.com/devinit/ddw-external-api/blob/dev/docs/spotlight-on-kenya.md) and [SoU](https://github.com/devinit/ddw-external-api/blob/dev/docs/spotlight-on-uganda.md) to add the start and end date columns (and new indicators as well), since we intend to make that API a public resource anyway;  killing two birds with one stone. @k8hughes, @edwinmp your thoughts? Otherwise all data is up to date as of now.

**Comment by edwinmp** [comment]
Yeah, adding a date range column to the documentation is good idea. Go nuts.
Since the analysts seem too busy to do it, I have to go through every indicator on the CMS, manually check if there's new data for each & update the `end_date` where required to draw in the latest data.
Next time, this'll be part of your data update testing @wakibi, cos no one knows which updates have been made for which indicator better than you and the analysts.

**Comment by wakibi** [comment]
README files updated for both SoK and SoU. PR approved by @edwinmp
